# coding: utf-8

"""
    Workload REST APIs

    APIs to be implemented by workloads for integration with Microsoft Fabric

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from fabric_api.models.error_details import ErrorDetails
from fabric_api.models.job_instance_status import JobInstanceStatus
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ItemJobInstanceState(BaseModel):
    """
    The job instance state.
    """ # noqa: E501
    status: JobInstanceStatus
    start_time_utc: Optional[datetime] = Field(default=None, description="The job instance start time.", alias="startTimeUtc")
    end_time_utc: Optional[datetime] = Field(default=None, description="The job instance end time.", alias="endTimeUtc")
    error_details: Optional[ErrorDetails] = Field(default=None, alias="errorDetails")
    __properties: ClassVar[List[str]] = ["status", "startTimeUtc", "endTimeUtc", "errorDetails"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ItemJobInstanceState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "start_time_utc",
                "end_time_utc",
            },
            exclude_none=True,
        )
        if self.error_details:
            _dict['errorDetails'] = self.error_details.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ItemJobInstanceState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "startTimeUtc": obj.get("startTimeUtc"),
            "endTimeUtc": obj.get("endTimeUtc"),
            "errorDetails": ErrorDetails.from_dict(obj.get("errorDetails")) if obj.get("errorDetails") is not None else None
        })
        return _obj


