# coding: utf-8

"""
    Workload REST APIs

    APIs to be implemented by workloads for integration with Microsoft Fabric

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum
from typing import Union, Any


try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class JobInvokeType(str, Enum):
    """
    The job invoke type.
    """

    """
    allowed enum values
    """
    UNKNOWNFUTUREVALUE = 'UnknownFutureValue'
    SCHEDULED = 'Scheduled'
    MANUAL = 'Manual'

    @classmethod
    def _missing_(cls, value):
        if isinstance(value, int):
            int_to_enum = {
                0: cls.UNKNOWNFUTUREVALUE,
                1: cls.SCHEDULED,
                2: cls.MANUAL
            }
            return int_to_enum.get(value)
        return None
    
    def __int__(self):
        enum_to_int = {
            self.UNKNOWNFUTUREVALUE: 0,
            self.SCHEDULED: 1,
            self.MANUAL: 2
        }
        return enum_to_int[self]

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of JobInvokeType from a JSON string"""
        return cls(json.loads(json_str))