# coding: utf-8

"""
    Workload REST APIs

    APIs to be implemented by workloads for integration with Microsoft Fabric

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class JobInstanceStatus(str, Enum):
    """
    The status of an item job instance.
    """

    """
    allowed enum values
    """
    NOTSTARTED = 'NotStarted'
    INPROGRESS = 'InProgress'
    COMPLETED = 'Completed'
    FAILED = 'Failed'
    CANCELLED = 'Cancelled'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of JobInstanceStatus from a JSON string"""
        return cls(json.loads(json_str))


